# vim:set ft=dockerfile:
FROM alpine:3.6

LABEL maintainer="Dashie <dashie@sigpipe.me>"

LABEL org.label-schema.license=MIT \
    org.label-schema.name=reel2bits-worker \
    org.label-schema.vcs-url=https://dev.sigpipe.me/dashie/reel2bits

RUN mkdir /app /data
COPY reel2bits /app/
COPY conf/ /app/
COPY entrypoint.sh /app/

RUN apk --no-cache --no-progress add sox taglib libmagic tzdata libmad boost libsndfile libid3tag

# Build audiowaveform
RUN apk add --no-cache --virtual .build-deps \
    cmake gcc g++ make pkgconfig git boost-dev gd-dev libmad-dev libsndfile-dev libid3tag-dev wget && \
    git clone https://github.com/bbcrd/audiowaveform.git /tmp/audiowaveform && cd /tmp/audiowaveform && \
    wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz -O gmock-1.8.0.tar.gz && tar xzf gmock-1.8.0.tar.gz && \
    ln -s googletest-release-1.8.0/googletest googletest && ln -s googletest-release-1.8.0/googlemock googlemock && \
    mkdir build && cd build && cmake .. && make && cp audiowaveform /app/ && cd .. && rm -rf audiowaveform && \
    apk del .build-deps

VOLUME ["/data"]

WORKDIR /app

EXPOSE 4000

ENTRYPOINT ["/app/entrypoint.sh"]

CMD ["/app/reel2bits", "worker"]
