"""Add updated to sounds

Revision ID: 052e645c59f4
Revises: 6b5a95742bb4
Create Date: 2016-12-31 18:19:50.261931

"""

# revision identifiers, used by Alembic.
revision = '052e645c59f4'
down_revision = '6b5a95742bb4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sound', sa.Column('updated', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sound', 'updated')
    ### end Alembic commands ###
