"""More infos fields

Revision ID: 14ecb77e9482
Revises: c517c68df56e
Create Date: 2016-12-31 20:53:55.649816

"""

# revision identifiers, used by Alembic.
revision = '14ecb77e9482'
down_revision = 'c517c68df56e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sound_info', sa.Column('bitrate', sa.Integer(), nullable=True))
    op.add_column('sound_info', sa.Column('bitrate_mode', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sound_info', 'bitrate_mode')
    op.drop_column('sound_info', 'bitrate')
    ### end Alembic commands ###
