"""empty message

Revision ID: 13ca6565de5b
Revises: 14ecb77e9482
Create Date: 2016-12-31 21:36:19.703528

"""

# revision identifiers, used by Alembic.
revision = '13ca6565de5b'
down_revision = '14ecb77e9482'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sound_info', sa.Column('type', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sound_info', 'type')
    ### end Alembic commands ###
