"""empty message

Revision ID: aeb6c1345690
Revises: fc50eb4e9b34
Create Date: 2017-01-01 01:11:11.549297

"""

# revision identifiers, used by Alembic.
revision = 'aeb6c1345690'
down_revision = 'fc50eb4e9b34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sound_info', sa.Column('waveform_error', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sound_info', 'waveform_error')
    ### end Alembic commands ###
