"""Add user locale

Revision ID: 3a6904b2b365
Revises: eb934854f591
Create Date: 2017-01-01 15:00:38.605336

"""

# revision identifiers, used by Alembic.
revision = '3a6904b2b365'
down_revision = 'eb934854f591'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('locale', sa.String(length=5), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'locale')
    ### end Alembic commands ###
