"""Add transcode fields

Revision ID: 01e6d591fe6f
Revises: b7bb72b21644
Create Date: 2017-01-03 22:11:44.663000

"""

# revision identifiers, used by Alembic.
revision = '01e6d591fe6f'
down_revision = 'b7bb72b21644'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sound', sa.Column('filename_transcoded', sa.String(length=255), nullable=True))
    op.add_column('sound', sa.Column('transcode_needed', sa.Boolean(), nullable=True))
    op.add_column('sound', sa.Column('transcode_state', sa.Integer(), server_default="0", nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sound', 'transcode_state')
    op.drop_column('sound', 'transcode_needed')
    op.drop_column('sound', 'filename_transcoded')
    ### end Alembic commands ###
