"""Addd Activity meta: deleted, pinned and undo

Revision ID: c1aa4c6b9acd
Revises: a34711408c8d
Create Date: 2019-03-27 06:50:03.818754

"""

# revision identifiers, used by Alembic.
revision = "c1aa4c6b9acd"
down_revision = "a34711408c8d"

from alembic import op  # noqa: E402
import sqlalchemy as sa  # noqa: E402


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("activity", sa.Column("meta_deleted", sa.Boolean(), nullable=True))
    op.add_column("activity", sa.Column("meta_pinned", sa.Boolean(), nullable=True))
    op.add_column("activity", sa.Column("meta_undo", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activity", "meta_undo")
    op.drop_column("activity", "meta_pinned")
    op.drop_column("activity", "meta_deleted")
    # ### end Alembic commands ###
