"""Add relation to Activity from Sound

Revision ID: da6070b2ce4e
Revises: c1aa4c6b9acd
Create Date: 2019-03-27 07:02:44.840655

"""

# revision identifiers, used by Alembic.
revision = 'da6070b2ce4e'
down_revision = 'c1aa4c6b9acd'

from alembic import op  # noqa: E402
import sqlalchemy as sa  # noqa: E402


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sound', sa.Column('activity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sound', 'activity', ['activity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sound', type_='foreignkey')
    op.drop_column('sound', 'activity_id')
    # ### end Alembic commands ###
