"""Add oauth apps table

Revision ID: 588930f4335e
Revises: da6070b2ce4e
Create Date: 2019-06-21 16:59:35.554167

"""

# revision identifiers, used by Alembic.
revision = "588930f4335e"
down_revision = "da6070b2ce4e"

from alembic import op  # noqa: E402
import sqlalchemy as sa  # noqa: E402


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_name", sa.String(length=255), nullable=True),
        sa.Column("redirect_uris", sa.String(length=255), nullable=True),
        sa.Column("scopes", sa.ARRAY(sa.String(length=255)), nullable=False),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("client_id", sa.String(length=255), nullable=True),
        sa.Column("client_secret", sa.String(length=255), nullable=True),
        sa.Column("inserted_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("app")
    # ### end Alembic commands ###
