"""Add user created_at and updated_at

Revision ID: 463da36c5bd5
Revises: d3745d45e223
Create Date: 2019-06-24 10:33:50.764691

"""

# revision identifiers, used by Alembic.
revision = "463da36c5bd5"
down_revision = "d3745d45e223"

from alembic import op  # noqa: E402
import sqlalchemy as sa  # noqa: E402


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    # ### end Alembic commands ###
