"""Migrate to client_metadata

Revision ID: dff4edfb26b6
Revises: 7df5c87e5fef
Create Date: 2021-02-23 22:59:23.112766

"""

# revision identifiers, used by Alembic.
revision = "dff4edfb26b6"
down_revision = "7df5c87e5fef"

from alembic import op  # noqa: E402
import sqlalchemy as sa  # noqa: E402


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("oauth2_client", "redirect_uri")
    op.drop_column("oauth2_client", "client_uri")
    op.drop_column("oauth2_client", "response_type")
    op.drop_column("oauth2_client", "client_name")
    op.drop_column("oauth2_client", "grant_type")
    op.drop_column("oauth2_client", "token_endpoint_auth_method")
    op.drop_column("oauth2_client", "scope")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("oauth2_client", sa.Column("scope", sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column(
        "oauth2_client",
        sa.Column("token_endpoint_auth_method", sa.VARCHAR(length=48), autoincrement=False, nullable=True),
    )
    op.add_column("oauth2_client", sa.Column("grant_type", sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column("oauth2_client", sa.Column("client_name", sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column("oauth2_client", sa.Column("response_type", sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column("oauth2_client", sa.Column("client_uri", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column("oauth2_client", sa.Column("redirect_uri", sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
