from setuptools import setup

setup(
    name="reel2bits",
    version="0.1",
    license="AGPL",
    python_requires=">=3.6",
    long_description=open("../README.md").read(),
    url="http://dev.sigpipe.me/DashieV3/reel2bits",
    author="Dashie",
    author_email="dashie@sigpipe.me",
    install_requires=[
        "Flask==1.1.2",
        "SQLAlchemy==1.3.23",
        "WTForms==2.3.3",
        "WTForms-Alchemy==0.17.0",
        "SQLAlchemy-Searchable==1.2.0",
        "SQLAlchemy-Utils==0.36.1",
        "Bootstrap-Flask==1.5.1",
        "Flask-Mail==0.9.1",
        "Flask-Migrate==2.7.0",
        "Flask-Reuploaded==0.5.0",
        "bcrypt==3.2.0",
        "pydub==0.24.1",
        "psycopg2-binary==2.8.6",
        "mutagen==1.45.1",
        "unidecode==1.2.0",
        "Flask_Babel==2.0.0",
        "texttable==1.6.3",
        "python-slugify==4.0.1",
        "python-magic==0.4.22",
        "redis==3.5.3",
        "celery==5.0.5",
        "flask-accept==0.0.6",
    ],
    setup_requires=["pytest-runner"],
    tests_require=["pytest==6.2.2", "pytest-cov==2.11.1", "jsonschema==3.2.0"],
)
